### ISSUE TITLE
AWS hpc7g + RHEL8 detected as Neoverse N1

### ISSUE THREAD

**Issue by fspiga** [archspec/archspec#140] opened 2024-01-17 11:53 UTC
```
[ec2-user@uabaluba ~]$ cd $HOME
[ec2-user@uabaluba ~]$ git clone https://github.com/spack/spack.git
[ec2-user@uabaluba ~]$ . spack/share/spack/setup-env.sh
[ec2-user@uabaluba ~]$ spack arch
linux-rhel8-neoverse_n1
```

which is odd because it is Graviton3 (Neoverse V1)
```
[ec2-user@uabaluba ~]$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  1
Core(s) per socket:  64
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
Model:               1
Stepping:            r1p1
BogoMIPS:            2100.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            1024K
L3 cache:            32768K
NUMA node0 CPU(s):   0-63
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs dcpodp svei8mm svebf16 i8mm bf16 dgh rng
```

I am using redHat 8.8
```
[ec2-user@uabaluba ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
```

Odd, isn't it? What could have gone wrong?

**Comment by alalazo** [comment] 2024-01-23 13:33
I think this is a duplicate of the issue I pinged you in https://github.com/archspec/archspec-json/issues/83 (which contains an explanation why things seems to be correct on the archspec side) I'm closing, but feel free to reopen if it seems another issue.

**Comment by dslarm** [comment] 2024-03-18 22:01
@alalazo @giordano - can you reopen this one, the change for #83 was only set to V2, and not V1, therefore this is still broken for V1 - the V2 patch needs to be duplicated to remove paca/pacg for V1.

**Comment by alalazo** [comment] 2024-03-19 07:04
@dslarm Should be fixed now

**Closed** 2024-03-19 07:03 UTC
Labels: duplicate
